"""Added signature table

Revision ID: 26e0a6e9acb7
Revises: 
Create Date: 2021-11-24 20:46:54.585576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26e0a6e9acb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('capture_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signature')
    # ### end Alembic commands ###
