"""added person and signature_set

Revision ID: 7bfbd98ecc34
Revises: 2512f9fa15d6
Create Date: 2021-12-03 19:55:27.855612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bfbd98ecc34'
down_revision = '2512f9fa15d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('passport', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_set',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('signature_id', postgresql.UUID(), nullable=True),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['signature_id'], ['signature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signature_set')
    op.drop_table('person')
    # ### end Alembic commands ###
