"""Added as-uuid

Revision ID: d2864ad7ce56
Revises: 791c37df40e9
Create Date: 2021-12-24 10:47:28.902429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2864ad7ce56'
down_revision = '791c37df40e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
