"""Added feature table

Revision ID: e20b89a5efcd
Revises: 26e0a6e9acb7
Create Date: 2021-11-24 21:15:49.528530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e20b89a5efcd'
down_revision = '26e0a6e9acb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('values', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('value_name', sa.String(length=32), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('signature_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['signature_id'], ['signature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature')
    # ### end Alembic commands ###
